// https://jwt.io/introduction/

//
// TESTING ROUTES
//

POST http://localhost:3000/users
Content-Type: application/json

{
	"username" : "Jakob",
	"password" : "jakob123",
	"email" : "jakob.opresnik@student.um.si"
}

### get user by JWT in Authorization header

GET http://localhost:3000/users/getByToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8

### get all users

GET http://localhost:3000/users/getAll

### get user by JWT in URL

GET http://localhost:3000/users/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8

### login user

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "Jakob",
    "password": "jakob123"
}

### logout user

GET http://localhost:3000/users/logout/Jakob

### delete user

DELETE http://localhost:3000/users/Jakob


### show all mbajk locations

GET http://localhost:3000/mbajk
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8

### insert mbajk location

POST http://localhost:3000/mbajk
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8
Content-Type: application/json

{
	"number" : "13",
    "name" : "TELEMACH - GLAVNI TRG - STARI PERON",
    "address" : "Glavni trg 20",
    "longitude" : "15.646833",
    "latitude" : " 46.5577328",
    "status" : "OPEN",
    "bikes" : "20",
    "capacity" : "20",
    "lastUpdateSensor" : "2022-05-05T09:51:18Z"
}


### insert bike path

POST http://localhost:3000/bikepath
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8
Content-Type: application/json

{
    "coordinates": [
          [
            15.627771080994304,
            46.60964403352395
          ],
          [
            15.627809999713907,
            46.609670000384426
          ],
          [
            15.627900000614453,
            46.60961000041628
          ]
    ]
}

### delete bike path

DELETE http://localhost:3000/bikepath
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8


### insert bike shed

POST http://localhost:3000/bikeshed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8
Content-Type: application/json

{
	"providerName" : "Center mobilnosti Maribor",
	"providerLink" : "https://mobilnost.si/storitve/kolesodvor/",
	"address" : "Partizanska cesta 50, 2000 Maribor",
	"quantity" : "20",
	"longitude" : "15.657430340440774",
	"latitude" : "46.56223243175121"
}

### delete bike shed

DELETE http://localhost:3000/bikeshed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8


### insert coridor

POST http://localhost:3000/coridor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8
Content-Type: application/json

{
    "coordinates": [
          [
            15.627771080994304,
            46.60964403352395
          ],
          [
            15.627809999713907,
            46.609670000384426
          ],
          [
            15.627900000614453,
            46.60961000041628
          ]
    ]
}

### delete coridor

DELETE http://localhost:3000/coridor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8


### insert bike stand

POST http://localhost:3000/stand
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8
Content-Type: application/json

{
    "name": "53 - Želežniška postaja Tabor",
    "parkSpots": "6",
    "longitude": "15.64577618045837",
    "latitude": "46.55169014946587"
}

### delete bike stand

DELETE http://localhost:3000/stand
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8


### insert bike tour path

POST http://localhost:3000/tourpath
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8
Content-Type: application/json

{
    "coordinates": [
        [
            15.627771080994304,
            46.60964403352395
        ],
        [
            15.627809999713907,
            46.609670000384426
        ],
        [
            15.627900000614453,
            46.60961000041628
        ]
    ]
}

### delete bike tour path

DELETE http://localhost:3000/tourpath
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpha29iIiwicGFzc3dvcmQiOiJqYWtvYjEyMyIsImlhdCI6MTY1MjAyMDgzMn0.G45kKShICGQJfOTYVsmU6n1dex9b2kPUtkUX721Hlh8
